In [1]:
import pandas as pd

In [2]:
prec_df = pd.read_csv(r"C:\Users\olive\Documents\GitHub\MilaClimateChangeHackathon2019\data\prepared_precipitation_data.csv")
prec_df['time'] = pd.to_datetime(prec_df['time'])
prec_df['time'] = [x.date() for x in prec_df['time'].tolist()]
prec_df = prec_df.reset_index(drop=True)
prec_df = prec_df.sort_values(['time', 'Grid']).set_index(['time','Grid'])

In [3]:
acc_df = pd.read_csv(r"C:\Users\olive\Documents\GitHub\MilaClimateChangeHackathon2019\data\AccidentData_GroupBy.csv")
acc_df['Grid'] = [x.replace('GRID_', '') for x in acc_df['Grid'].tolist()]
acc_df = acc_df.rename({'Date of collision': 'time'}, axis=1)
acc_df['time'] = pd.to_datetime(acc_df['time'])
acc_df['time'] = [x.date() for x in acc_df['time'].tolist()]
acc_df = acc_df.reset_index(drop=True)
acc_df = acc_df.sort_values(['time', 'Grid']).set_index(['time', 'Grid'])

In [4]:
acc_df.head()

                                            Implied vehicules  Serious injury  \
time       Grid
2012-01-01 45.458333155|-73.625002695                      24               1
           45.458333155|-73.70833602500002                  1               0
           45.458333155|-73.791669355                       4               0
           45.458333155|-73.875002685                       4               0
           45.541666485|-73.541669365                      28               0

                                            Light injury  Total victims  \
time       Grid
2012-01-01 45.458333155|-73.625002695                  6              7
           45.458333155|-73.70833602500002             0              0
           45.458333155|-73.791669355                  0              0
           45.458333155|-73.875002685                  0              0
           45.541666485|-73.541669365                  5              5

                                            Trucks and car  Heavy tractor  \
time       Grid
2012-01-01 45.458333155|-73.625002695                   15              0
           45.458333155|-73.70833602500002               1              0
           45.458333155|-73.791669355                    2              0
           45.458333155|-73.875002685                    3              0
           45.541666485|-73.541669365                   22              0

                                            Tool equipment  Bus  Bicycle  \
time       Grid
2012-01-01 45.458333155|-73.625002695                    1    0        0
           45.458333155|-73.70833602500002               0    0        0
           45.458333155|-73.791669355                    0    0        0
           45.458333155|-73.875002685                    0    0        0
           45.541666485|-73.541669365                    0    0        0

                                            Moped  ...  Motorcycle injuries  \
time       Grid                                    ...
2012-01-01 45.458333155|-73.625002695           0  ...                    0
           45.458333155|-73.70833602500002      0  ...                    0
           45.458333155|-73.791669355           0  ...                    0
           45.458333155|-73.875002685           0  ...                    0
           45.541666485|-73.541669365           0  ...                    0

                                            Motorcycle victims  Bicycle death  \
time       Grid
2012-01-01 45.458333155|-73.625002695                        0              0
           45.458333155|-73.70833602500002                   0              0
           45.458333155|-73.791669355                        0              0
           45.458333155|-73.875002685                        0              0
           45.541666485|-73.541669365                        0              0

                                            Bicycle injury  Bicycle victims  \
time       Grid
2012-01-01 45.458333155|-73.625002695                    0                0
           45.458333155|-73.70833602500002               0                0
           45.458333155|-73.791669355                    0                0
           45.458333155|-73.875002685                    0                0
           45.541666485|-73.541669365                    0                0

                                            Severity: Inferior damages  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                5
           45.458333155|-73.70833602500002                           0
           45.458333155|-73.791669355                                1
           45.458333155|-73.875002685                                1
           45.541666485|-73.541669365                                5

                                            Severity: Material damages  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                3
           45.458333155|-73.70833602500002                           1
           45.458333155|-73.791669355                                1
           45.458333155|-73.875002685                                2
           45.541666485|-73.541669365                                3

                                            Severity: Serious injury  \
time       Grid
2012-01-01 45.458333155|-73.625002695                              1
           45.458333155|-73.70833602500002                         0
           45.458333155|-73.791669355                              0
           45.458333155|-73.875002685                              0
           45.541666485|-73.541669365                              0

                                            Severity: Light injury  \
time       Grid
2012-01-01 45.458333155|-73.625002695                            2
           45.458333155|-73.70833602500002                       0
           45.458333155|-73.791669355                            0
           45.458333155|-73.875002685                            0
           45.541666485|-73.541669365                            4

                                            Severity: Death
time       Grid
2012-01-01 45.458333155|-73.625002695                     0
           45.458333155|-73.70833602500002                0
           45.458333155|-73.791669355                     0
           45.458333155|-73.875002685                     0
           45.541666485|-73.541669365                     0

[5 rows x 30 columns]

In [5]:
prec_df.head()

                                                  lat        lon  \
time       Grid
2012-01-01 45.458333155|-73.625002695       45.458333 -73.625003
           45.458333155|-73.70833602500002  45.458333 -73.708336
           45.458333155|-73.791669355       45.458333 -73.791669
           45.458333155|-73.875002685       45.458333 -73.875003
           45.458333155|-73.958336015       45.458333 -73.958336

                                            pr_CNRM-CM5_historical_rcp26_(kg m-2 d-1)  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                        5.517578
           45.458333155|-73.70833602500002                                   5.541992
           45.458333155|-73.791669355                                        5.615234
           45.458333155|-73.875002685                                        5.651855
           45.458333155|-73.958336015                                        5.737305

                                            pr_CNRM-CM5_historical_rcp45_(kg m-2 d-1)  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                       -0.000092
           45.458333155|-73.70833602500002                                  -0.000092
           45.458333155|-73.791669355                                        0.170807
           45.458333155|-73.875002685                                        0.610260
           45.458333155|-73.958336015                                        0.732330

                                            pr_CNRM-CM5_historical_rcp85_(kg m-2 d-1)  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                        1.501404
           45.458333155|-73.70833602500002                                   1.574646
           45.458333155|-73.791669355                                        1.599060
           45.458333155|-73.875002685                                        1.586853
           45.458333155|-73.958336015                                        1.538025

                                            pr_MIROC-ESM-CHEM_historical_rcp26_(kg m-2 d-1)  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                              0.976471
           45.458333155|-73.70833602500002                                         0.939850
           45.458333155|-73.791669355                                              0.927643
           45.458333155|-73.875002685                                              1.525818
           45.458333155|-73.958336015                                              1.501404

                                            pr_MIROC-ESM-CHEM_historical_rcp45_(kg m-2 d-1)  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                              6.542969
           45.458333155|-73.70833602500002                                         6.396484
           45.458333155|-73.791669355                                              6.298828
           45.458333155|-73.875002685                                              6.262207
           45.458333155|-73.958336015                                              6.188965

                                            pr_MIROC-ESM-CHEM_historical_rcp85_(kg m-2 d-1)  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                             -0.000092
           45.458333155|-73.70833602500002                                        -0.000092
           45.458333155|-73.791669355                                             -0.000092
           45.458333155|-73.875002685                                             -0.000092
           45.458333155|-73.958336015                                             -0.000092

                                            pr_MIROC-ESM_historical_rcp26_(kg m-2 d-1)  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                         0.891022
           45.458333155|-73.70833602500002                                    0.866608
           45.458333155|-73.791669355                                         0.878815
           45.458333155|-73.875002685                                         1.147400
           45.458333155|-73.958336015                                         1.489197

                                            pr_MIROC-ESM_historical_rcp45_(kg m-2 d-1)  \
time       Grid
2012-01-01 45.458333155|-73.625002695                                        14.624145
           45.458333155|-73.70833602500002                                   14.343384
           45.458333155|-73.791669355                                        14.404419
           45.458333155|-73.875002685                                        14.026001
           45.458333155|-73.958336015                                        13.769653

                                            ...  MONTH_3  MONTH_4  MONTH_5  \
time       Grid                             ...
2012-01-01 45.458333155|-73.625002695       ...        0        0        0
           45.458333155|-73.70833602500002  ...        0        0        0
           45.458333155|-73.791669355       ...        0        0        0
           45.458333155|-73.875002685       ...        0        0        0
           45.458333155|-73.958336015       ...        0        0        0

                                            MONTH_6  MONTH_7  MONTH_8  \
time       Grid
2012-01-01 45.458333155|-73.625002695             0        0        0
           45.458333155|-73.70833602500002        0        0        0
           45.458333155|-73.791669355             0        0        0
           45.458333155|-73.875002685             0        0        0
           45.458333155|-73.958336015             0        0        0

                                            MONTH_9  MONTH_10  MONTH_11  \
time       Grid
2012-01-01 45.458333155|-73.625002695             0         0         0
           45.458333155|-73.70833602500002        0         0         0
           45.458333155|-73.791669355             0         0         0
           45.458333155|-73.875002685             0         0         0
           45.458333155|-73.958336015             0         0         0

                                            MONTH_12
time       Grid
2012-01-01 45.458333155|-73.625002695              0
           45.458333155|-73.70833602500002         0
           45.458333155|-73.791669355              0
           45.458333155|-73.875002685              0
           45.458333155|-73.958336015              0

[5 rows x 45 columns]

In [6]:
merged_df = pd.concat([acc_df, prec_df], axis=1).fillna(0)

In [7]:
merged_df.head()

                                            Implied vehicules  Serious injury  \
time       Grid
2012-01-01 45.458333155|-73.625002695                    24.0             1.0
           45.458333155|-73.70833602500002                1.0             0.0
           45.458333155|-73.791669355                     4.0             0.0
           45.458333155|-73.875002685                     4.0             0.0
           45.458333155|-73.958336015                     0.0             0.0

                                            Light injury  Total victims  \
time       Grid
2012-01-01 45.458333155|-73.625002695                6.0            7.0
           45.458333155|-73.70833602500002           0.0            0.0
           45.458333155|-73.791669355                0.0            0.0
           45.458333155|-73.875002685                0.0            0.0
           45.458333155|-73.958336015                0.0            0.0

                                            Trucks and car  Heavy tractor  \
time       Grid
2012-01-01 45.458333155|-73.625002695                 15.0            0.0
           45.458333155|-73.70833602500002             1.0            0.0
           45.458333155|-73.791669355                  2.0            0.0
           45.458333155|-73.875002685                  3.0            0.0
           45.458333155|-73.958336015                  0.0            0.0

                                            Tool equipment  Bus  Bicycle  \
time       Grid
2012-01-01 45.458333155|-73.625002695                  1.0  0.0      0.0
           45.458333155|-73.70833602500002             0.0  0.0      0.0
           45.458333155|-73.791669355                  0.0  0.0      0.0
           45.458333155|-73.875002685                  0.0  0.0      0.0
           45.458333155|-73.958336015                  0.0  0.0      0.0

                                            Moped  ...  MONTH_3  MONTH_4  \
time       Grid                                    ...
2012-01-01 45.458333155|-73.625002695         0.0  ...        0        0
           45.458333155|-73.70833602500002    0.0  ...        0        0
           45.458333155|-73.791669355         0.0  ...        0        0
           45.458333155|-73.875002685         0.0  ...        0        0
           45.458333155|-73.958336015         0.0  ...        0        0

                                            MONTH_5  MONTH_6  MONTH_7  \
time       Grid
2012-01-01 45.458333155|-73.625002695             0        0        0
           45.458333155|-73.70833602500002        0        0        0
           45.458333155|-73.791669355             0        0        0
           45.458333155|-73.875002685             0        0        0
           45.458333155|-73.958336015             0        0        0

                                            MONTH_8  MONTH_9  MONTH_10  \
time       Grid
2012-01-01 45.458333155|-73.625002695             0        0         0
           45.458333155|-73.70833602500002        0        0         0
           45.458333155|-73.791669355             0        0         0
           45.458333155|-73.875002685             0        0         0
           45.458333155|-73.958336015             0        0         0

                                            MONTH_11  MONTH_12
time       Grid
2012-01-01 45.458333155|-73.625002695              0         0
           45.458333155|-73.70833602500002         0         0
           45.458333155|-73.791669355              0         0
           45.458333155|-73.875002685              0         0
           45.458333155|-73.958336015              0         0

[5 rows x 75 columns]

In [8]:
merged_df = merged_df.drop(['lat', 'lon'], axis=1)
merged_df = merged_df.reset_index(drop=True)

In [9]:
merged_df.head()

,Implied vehicules,Serious injury,Light injury,Total victims,Trucks and car,Heavy tractor,Tool equipment,Bus,Bicycle,Moped,...,MONTH_3,MONTH_4,MONTH_5,MONTH_6,MONTH_7,MONTH_8,MONTH_9,MONTH_10,MONTH_11,MONTH_12
0,24.0,1.0,6.0,7.0,15.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,4.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,4.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
merged_df.to_csv(r"C:\Users\olive\Documents\GitHub\MilaClimateChangeHackathon2019\data\Final_Dataset.csv")